# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-07 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorumvaruygulama', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorular',
            name='isim',
        ),
        migrations.RemoveField(
            model_name='sorular',
            name='soyisim',
        ),
    ]
