# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-07 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorumvaruygulama', '0002_auto_20190107_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorular',
            name='isim',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sorular',
            name='soyisim',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
