# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-09 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorumvaruygulama', '0004_auto_20190107_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanicilar',
            name='soru_sayisi',
            field=models.IntegerField(default=0),
        ),
    ]
