# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-09 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorumvaruygulama', '0005_kullanicilar_soru_sayisi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kullanicilar',
            options={'ordering': ['-soru_sayisi', '-id']},
        ),
        migrations.AlterField(
            model_name='sorular',
            name='icerik',
            field=models.CharField(max_length=5000),
        ),
    ]
