# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-10 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorumvaruygulama', '0006_auto_20190109_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyurular',
            name='dosyalar',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
