# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-10 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorumvaruygulama', '0007_duyurular_dosyalar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duyurular',
            name='dosyalar',
        ),
    ]
