# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-15 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorumvaruygulama', '0008_remove_duyurular_dosyalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyurular',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
